export const siteConfig = {
  shopName: 'MEMOLACES',
  slogan: 'More Than Shoelaces',
  announcement: 'Freeship cho đơn từ 299K • Tư vấn chọn độ dài dây giày qua Zalo',
  tagline: 'Thay Dây Mới - Làm Mới Cả Đôi Giày',
  secondarySlogans: [
    'Thay Dây Mới - Làm Mới Cả Đôi Giày',
    'Từ Chi Tiết Nhỏ, Tạo Nên Khác Biệt Lớn',
    'Nâng Tầm Đôi Giày Mỗi Ngày',
  ],
  shortDescription:
    'MEMOLACES chuyên dây giày, phụ kiện trang trí, vệ sinh và bảo quản giày. Khám phá nhiều lựa chọn màu sắc, kiểu dây và độ dài phù hợp với đôi giày của bạn.',
  description:
    'Memolaces xây dựng hệ sinh thái phụ kiện dành cho người yêu giày, từ dây giày, phụ kiện custom đến giải pháp vệ sinh và bảo quản.',
  categories: [
    {
      name: 'Dây Giày',
      href: '/products?category=Dây%20Giày',
      description: 'Dây giày phản quang, oval, flat, tròn, custom và theo mẫu giày.',
      children: [
        'Dây giày phản quang',
        'Dây giày oval',
        'Dây giày flat',
        'Dây giày tròn',
        'Dây giày custom',
        'Dây giày theo thương hiệu/mẫu giày',
      ],
    },
    {
      name: 'Phụ Kiện Trang Trí',
      href: '/products?category=Phụ%20Kiện%20Trang%20Trí',
      description: 'Charm giày, dây treo, tag phụ kiện, khóa và đầu tip thay thế.',
      children: ['Charm giày', 'Dây treo trang trí', 'Tag phụ kiện', 'Khóa và đầu tip thay thế'],
    },
    {
      name: 'Vệ Sinh Giày',
      href: '/products?category=Vệ%20Sinh%20Giày',
      description: 'Dụng cụ làm sạch, khăn lau và bộ kit chăm sóc giày hằng ngày.',
      children: ['Bàn chải vệ sinh', 'Khăn lau giày', 'Dung dịch làm sạch', 'Bộ kit chăm sóc giày'],
    },
    {
      name: 'Bảo Quản Giày',
      href: '/products?category=Bảo%20Quản%20Giày',
      description: 'Giải pháp cất giữ, bảo vệ form và kéo dài tuổi thọ đôi giày.',
      children: ['Túi đựng giày', 'Hộp bảo quản', 'Gói hút ẩm', 'Phụ kiện chống nhăn'],
    },
  ],
  laceTypes: [
    { label: 'Dây flat', href: '/products?style=flat' },
    { label: 'Dây oval', href: '/products?style=oval' },
    { label: 'Dây rope/tròn', href: '/products?style=rope' },
    { label: 'Dây phản quang', href: '/products?style=reflective' },
    { label: 'Dây waxed', href: '/products?style=waxed' },
    { label: 'Dây printed/custom', href: '/products?style=printed' },
    { label: 'Dây theo mẫu giày', href: '/products?category=Dây%20Giày' },
  ],
  lengths: [
    { label: '100cm', href: '/products?length=100cm', text: 'Giày thấp/cổ thấp, ít lỗ xỏ' },
    { label: '120cm', href: '/products?length=120cm', text: 'Giày phổ thông' },
    { label: '140cm', href: '/products?length=140cm', text: 'Sneaker nhiều lỗ xỏ' },
    { label: '160cm', href: '/products?length=160cm', text: 'Cổ cao hoặc buộc dài' },
    { label: '180cm', href: '/products?length=180cm', text: 'Boots/cổ cao/dây dài' },
  ],
  styles: [
    { label: 'OFFWHITE “SHOELACES”', value: 'shoelaces', href: '/products?style=shoelaces' },
    { label: 'Jordan', value: 'jordan', href: '/products?style=jordan' },
    { label: 'Dunk/SB', value: 'dunk', href: '/products?style=dunk' },
    { label: 'Yeezy/350', value: 'yeezy', href: '/products?style=yeezy' },
    { label: 'Air Max', value: 'air-max', href: '/products?style=air-max' },
    { label: 'MLB', value: 'mlb', href: '/products?style=mlb' },
    { label: 'Converse/Vans', value: 'converse-vans', href: '/products?style=converse-vans' },
  ],
  reasonsToChoose: [
    'Nhiều lựa chọn màu sắc và kích thước',
    'Dễ phối với nhiều dòng giày phổ biến',
    'Chất liệu bền, dễ vệ sinh',
    'Hình ảnh sản phẩm sát thực tế',
    'Đóng gói cẩn thận',
    'Hỗ trợ tư vấn lựa chọn độ dài phù hợp',
    'Liên tục cập nhật mẫu mới',
  ],
  phone: '0862 227 899',
  phoneHref: 'tel:0862227899',
  zalo: 'https://zalo.me/0862227899',
  email: 'memolaces.vn@gmail.com',
  address: 'Địa chỉ shop đang cập nhật',
  facebook: '#',
  tiktok: '#',
  canonicalDomain: 'https://memolaces.com',
  ogImage: '/images/og-memolaces.jpg',
  primaryColor: '#0f766e',
};
